name: Build and Deploy to ECR

on:
  push:
    branches: [main]  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build backend image
        working-directory: api
        run: |
          docker build -t backend-image .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push backend image to ECR
        run: |
          docker tag backend-image:latest 569667774725.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 569667774725.dkr.ecr.us-east-1.amazonaws.com/backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build frontend image
        working-directory: client
        run: |
          docker build -t frontend-image .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push frontend image to ECR
        run: |
          docker tag frontend-image:latest 569667774725.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 569667774725.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
